services:
  postgres_shining_db:
    image: postgres
    container_name: postgres_shining_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes: 
      - pg_shining-db:/var/lib/postgresql/data

  node_shining_app:
    container_name: node_shining_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_shining_db
    env_file:
      - .env

volumes:
  pg_shining-db: